### ISSUE TITLE
リンクテキスト修正

### ISSUE THREAD

**Issue by Junko-Koide** [d-zero-dev/a11y-checklist#7]
チェックリスト詳細から一覧ページに戻るリンクテキストが「◀ チェック項目一覧」になっていますが、該当ページタイトルとH1は「アクセシビリティチェックリスト」になっています。どちらかに統一お願いします。

**Comment by YusukeHirao** [comment]
ヘッダ追加に伴いリンク自体を削除しました。
https://github.com/d-zero-dev/a11y-checklist/commit/3876e0946bc9a3fc28c4da53c7b4b75aae7b23b1#diff-fcb7e068c8384f7a5633aca5fd491e63c526608ca570935f09742e18c55e09b1L37-L39
